# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "floppy" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0a352745-dc66-4ed4-aad0-b43c92dd446b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0a352745-dc66-4ed4-aad0-b43c92dd446b".device = "/dev/disk/by-uuid/0a352745-dc66-4ed4-aad0-b43c92dd446b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4702-E5D2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
